[project]
name = "png2svg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sam84-TECH", email = "samaaashley.kouyele@centrale-casablanca.ma" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo>=0.25.1",
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.10",
]
